# Generated by Django 5.2.1 on 2026-06-12 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_rankingjob_rankingresult'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='certifications',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='candidate',
            name='education_level',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
        migrations.AddField(
            model_name='candidate',
            name='location',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='rankingjob',
            name='role_type',
            field=models.CharField(blank=True, default='general', max_length=64),
        ),
        migrations.AddField(
            model_name='rankingjob',
            name='weights_used',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='rankingresult',
            name='confidence_score',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='rankingresult',
            name='future_roles',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='rankingresult',
            name='growth_forecast',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='rankingresult',
            name='interview_questions',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='rankingresult',
            name='learning_path',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='rankingresult',
            name='potential_score',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='rankingresult',
            name='recruiter_recommendation',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='rankingresult',
            name='risk_level',
            field=models.CharField(choices=[('low', 'Low Risk'), ('medium', 'Medium Risk'), ('high', 'High Risk')], default='medium', max_length=16),
        ),
        migrations.AddField(
            model_name='rankingresult',
            name='role_fit_analysis',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='rankingresult',
            name='salary_fit',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='rankingresult',
            name='why_rejected',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='rankingresult',
            name='why_selected',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='full_name',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AddIndex(
            model_name='candidate',
            index=models.Index(fields=['full_name'], name='api_candida_full_na_42afce_idx'),
        ),
        migrations.AddIndex(
            model_name='candidate',
            index=models.Index(fields=['years_experience'], name='api_candida_years_e_50ba5f_idx'),
        ),
        migrations.AddIndex(
            model_name='rankingjob',
            index=models.Index(fields=['-created_at'], name='api_ranking_created_f9e8c8_idx'),
        ),
        migrations.AddIndex(
            model_name='rankingresult',
            index=models.Index(fields=['ranking_job', 'rank'], name='api_ranking_ranking_42a99a_idx'),
        ),
        migrations.AddIndex(
            model_name='rankingresult',
            index=models.Index(fields=['final_score'], name='api_ranking_final_s_91c38f_idx'),
        ),
    ]
