# Generated by Django 5.2.1 on 2026-06-12 06:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('profile_text', models.TextField(blank=True, default='')),
                ('skills', models.TextField(blank=True, default='')),
                ('years_experience', models.FloatField(default=0.0)),
                ('github_url', models.URLField(blank=True, null=True)),
                ('open_to_work', models.BooleanField(default=False)),
                ('recruiter_response_rate', models.FloatField(default=0.0)),
                ('interview_completion_rate', models.FloatField(default=0.0)),
                ('offer_acceptance_rate', models.FloatField(default=0.0)),
                ('profile_completeness', models.FloatField(default=0.0)),
                ('salary_expectation', models.CharField(blank=True, default='', max_length=128)),
                ('relocation_preference', models.CharField(blank=True, default='', max_length=128)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('required_skills', models.TextField(blank=True, default='')),
                ('preferred_skills', models.TextField(blank=True, default='')),
                ('min_experience', models.FloatField(default=0.0)),
                ('industry', models.CharField(blank=True, default='', max_length=128)),
                ('behavioral_expectations', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='CandidateEmbedding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vector', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('candidate', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='embedding', to='api.candidate')),
            ],
        ),
    ]
