# Generated by Django 5.2.1 on 2026-06-12 07:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_candidatejob'),
    ]

    operations = [
        migrations.CreateModel(
            name='RankingJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='', max_length=255)),
                ('job_description', models.TextField(blank=True, default='')),
                ('job_analysis', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='RankingResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.PositiveIntegerField()),
                ('semantic_score', models.FloatField(default=0.0)),
                ('skill_score', models.FloatField(default=0.0)),
                ('experience_score', models.FloatField(default=0.0)),
                ('recruitability_score', models.FloatField(default=0.0)),
                ('llm_score', models.FloatField(default=0.0)),
                ('final_score', models.FloatField(default=0.0)),
                ('strengths', models.JSONField(default=list)),
                ('weaknesses', models.JSONField(default=list)),
                ('missing_skills', models.JSONField(default=list)),
                ('recruiter_summary', models.TextField(blank=True, default='')),
                ('payload', models.JSONField(default=dict)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.candidate')),
                ('ranking_job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='api.rankingjob')),
            ],
        ),
    ]
